In [1]:
import numpy as np

In [22]:
l = [[1, 2, 3], [4, 5], [6, 7, 8]]
dis = np.array([[0,0.5,0.7],
       [0,0,0.3],
       [0,0,0]])
results = 0
results2 = 0
n = len(l)
for c1_pos in range(n):
    for c2_pos in range(n):
        if c1_pos < c2_pos:
            c1 = l[c1_pos]
            c2 = l[c2_pos]
            dist = dis[c1_pos,c2_pos]
            for v1 in c1:
                for v2 in c2:
                    results += (v1+v2-dist)**2
                    results2 += v1**2 + v2**2 +2*v1*v2+dist**2-2*(v1+v2)*dist
results

1611.65

In [68]:
import torch
idx = torch.tensor([1,2])
tensor_2d = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8]])
tensor_2d[idx,]

tensor([[5, 6, 7, 8],
        [5, 6, 7, 8]])

In [ ]:
general_cl_id = [torch.tensor([0,0,0,1,1,1]),torch.tensor([2,2,3,4,5,5])]
general_mask = [torch.tensor([0,1,2,3,4,5]),torch.tensor([0,1,2,3,4,5])]

In [59]:
import numpy as np
cl_id = np.array([0, 0, 0, 1, 1, 2, 2, 2])
mask = np.array([0,1,2,3,4,5,6,7])
dis = np.array([[0, 0.5, 0.7], [0, 0, 0.3], [0, 0, 0]])
gamma = np.array([1,2,3,4,5,6,7,8])
# Create a dictionary to group elements by their cluster IDs
grouped_data = {}
for i, cluster_id in enumerate(cl_id):
    if cluster_id not in grouped_data:
        grouped_data[cluster_id] = []
    grouped_data[cluster_id].append(mask[i])
# Convert the grouped data to a list of NumPy arrays
l = [np.array(grouped_data[cluster_id]) for cluster_id in sorted(grouped_data.keys())]
# Create an upper triangular matrix for the results
results = 0
 
# Vectorized computation of the results
for c1_pos in range(len(l)):
    for c2_pos in range(c1_pos + 1, len(l)):
        c1 = l[c1_pos]
        c2 = l[c2_pos]
        dist = dis[c1_pos, c2_pos]
        v1, v2 = np.meshgrid(c1, c2)
        results += np.sum((gamma[v1] + gamma[v2] - dist) ** 2)
print(results)

1611.65


In [58]:
import numpy as np

cl_id = [0, 0, 0, 1, 1, 2, 2, 2]
mask = [0,1,2,3,4,5,6,7]
dis = np.array([[0, 0.5, 0.7], [0, 0, 0.3], [0, 0, 0]])
gamma = np.array([1,2,3,4,5,6,7,8])

# Create a dictionary to group elements by their cluster IDs
grouped_data = {}
for i, cluster_id in enumerate(cl_id):
    if cluster_id not in grouped_data:
        grouped_data[cluster_id] = []
    grouped_data[cluster_id].append(mask[i])

# Convert the grouped data to a list of NumPy arrays
l = [np.array(grouped_data[cluster_id]) for cluster_id in sorted(grouped_data.keys())]

# Create an upper triangular matrix for the results
results = 0

for c1_pos in range(len(l)):
    for c2_pos in range(c1_pos + 1, len(l)):
        c1 = l[c1_pos]
        c2 = l[c2_pos]
        dist = dis[c1_pos, c2_pos]
        for v1 in c1:
            for v2 in c2:
                results += (gamma[v1]+gamma[v2]-dist)**2

print(results)


1611.65


In [55]:
gamma = np.array([1,2,3,4,5,6,7,8])
gamma.pos[4,6]

AttributeError: 'numpy.ndarray' object has no attribute 'pos'

In [51]:
c1[:, np.newaxis]+c2

array([[10, 11, 12],
       [11, 12, 13]])

array([6, 7, 8])

In [46]:
import numpy as np

cl_id = [0, 0, 0, 1, 1, 2, 2, 2]
mask = [1, 2, 3, 4, 5, 6, 7, 8]
dis = np.array([[0, 0.5, 0.7], [0, 0, 0.3], [0, 0, 0]])

# Group the mask values based on cl_id
grouped_mask = [np.array(mask)[np.array(cl_id) == i] for i in np.unique(cl_id)]

# Create an upper triangular matrix for the results
n = len(np.unique(cl_id))
results = np.triu(np.zeros((n, n), dtype=float), k=1)

for c1_pos in range(n):
    for c2_pos in range(c1_pos + 1, n):
        c1 = grouped_mask[c1_pos]
        c2 = grouped_mask[c2_pos]
        dist = dis[c1_pos, c2_pos]

        # Vectorized computation for the squared differences
        diff = c1[:, np.newaxis] + c2 - dist
        results[c1_pos, c2_pos] = np.sum(diff**2)

# Calculate the total sum of squared differences
total_results = np.sum(results)
print(total_results)


1611.65


In [47]:
c1

array([4, 5])

In [43]:
import torch
 
cl_id = torch.tensor([0, 0, 0, 1, 1, 2, 2, 2])
mask = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
dis = torch.tensor([[0, 0.5, 0.7], [0, 0, 0.3], [0, 0, 0]])
 
# Group the mask values based on cl_id
grouped_mask = [mask[cl_id == i] for i in torch.unique(cl_id)]
 
# Create an upper triangular matrix for the results
n = len(torch.unique(cl_id))
results = torch.triu(torch.zeros((n, n), dtype=torch.float), diagonal=1)
 
# Calculate the pairwise distances and squared differences
for c1_pos in range(n):
    for c2_pos in range(c1_pos + 1, n):
        c1 = grouped_mask[c1_pos]
        c2 = grouped_mask[c2_pos]
        dist = dis[c1_pos, c2_pos]
        c1 = c1.unsqueeze(1)
        diff = c1 + c2 - dist
        results[c1_pos, c2_pos] = torch.sum(diff**2)
 
# Calculate the total sum of squared differences
total_results = torch.sum(results)

In [45]:
c1

tensor([[4],
        [5]])

In [33]:
import numpy as np

l = [[1, 2, 3], [4, 5], [6, 7, 8]]
dis = np.array([[0, 0.5, 0.7],
                [0, 0, 0.3],
                [0, 0, 0]])

l_lens = np.array([len(x) for x in l])
max_len = l_lens.max()
l_padded = np.array([x + [0]*(max_len-len(x)) for x in l])

v1 = l_padded[:, :, np.newaxis]  # (3, 3, 1)
v2 = l_padded[:, np.newaxis, :]  # (3, 1, 3)

v1_squared = v1**2  # (3, 3, 3)
v2_squared = v2**2  # (3, 3, 3)
v1_v2 = 2 * v1 * v2  # (3, 3, 3)

distances = dis[:, :, np.newaxis, np.newaxis]  # (3, 3, 1, 1)
dist_squared = distances**2  # (3, 3, 1, 1)
dist_term = 2 * (v1 + v2) * distances  # (3, 3, 3, 1)

# Summing all the terms
results_vectorized = np.sum(v1_squared + v2_squared + v1_v2 + dist_squared - dist_term, axis=(0, 1, 2))

print(results_vectorized)


[2000.49 2432.49 2288.49]


In [32]:
l_arr 


array([[1., 2., 3.],
       [4., 5., 0.],
       [6., 7., 8.]])

In [19]:
dis[1,2]

TypeError: list indices must be integers or slices, not tuple

In [10]:
c1 = np.array([1, 2, 3])
c2 = np.array([4, 5])

v1_matrix, v2_matrix = np.meshgrid(c1, c2)
temp = v1_matrix ** 2 + v2_matrix ** 2
results = np.sum(temp)


print(results)

[[17 20 25]
 [26 29 34]]
151


In [11]:
# Define a list of lists
lists = [[1, 2, 3], [4, 5], [6, 7, 8]]

# Convert the list of lists to a list of NumPy arrays
arrays = [np.array(lst) for lst in lists]

# Create mesh grids for each array and store them in a list
meshgrids = [np.meshgrid(arr1, arr2) for arr1, arr2 in zip(arrays, arrays[1:])]

# Calculate the squares of each element in the mesh grids
squared_meshgrids = [arr1 ** 2 + arr2 ** 2 for arr1, arr2 in meshgrids]

# Sum all the squared mesh grids
results = sum(squared_meshgrids)

print(results)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 